# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrentdata',
            name='name',
            field=models.TextField(),
        ),
    ]
