# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0002_auto_20170801_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentdata',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间'),
        ),
    ]
